# Generated by Django 5.1.4 on 2026-03-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_project_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='visible_on_board',
            field=models.BooleanField(default=True),
        ),
    ]
