# Generated by Django 5.1.4 on 2026-08-31 15:00

from django.db import migrations, models


def dedupe_status_names(apps, schema_editor):
    """Rename duplicate (project, name) statuses so the unique constraint can be added.

    Existing databases predate the constraint and may already hold duplicates; without
    this the AddConstraint below fails and the deploy dies mid-migration.
    """
    Status = apps.get_model('projects', 'Status')

    # Case-sensitive, matching the constraint itself — do not rename statuses
    # that only differ in case, since those do not violate it.
    seen = set()
    duplicates = []
    for status in Status.objects.order_by('project_id', 'pk').iterator():
        key = (status.project_id, status.name)
        if key in seen:
            duplicates.append(status)
        else:
            seen.add(key)

    for status in duplicates:
        suffix = 2
        while True:
            base = status.name[:100 - len(str(suffix)) - 1]
            new_name = f'{base}-{suffix}'
            if (status.project_id, new_name) not in seen:
                break
            suffix += 1
        seen.add((status.project_id, new_name))
        status.name = new_name
        status.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_visible_on_board'),
    ]

    operations = [
        migrations.RunPython(dedupe_status_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_status_name_per_project'),
        ),
    ]
