# Generated by Django 5.1.4 on 2026-08-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_phase_b_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
