# Generated by Django 5.1.4 on 2026-09-28 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskListFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_statuses', models.ManyToManyField(blank=True, related_name='hidden_on_task_lists', to='projects.status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_list_filters', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_list_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='unique_task_list_filter_per_user_project')],
            },
        ),
    ]
