# Generated by Django 5.1.4 on 2026-09-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_task_list_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttasklistfilter',
            name='shown_priorities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
