# Generated by Django 5.1.4 on 2026-10-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_project_key_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
