# Generated by Django 5.1.4 on 2026-10-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_project_hourly_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_hold", "On hold"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                db_default="active",
                default="active",
                max_length=20,
            ),
        ),
    ]
