# Generated by Django 5.1.4 on 2026-10-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="billing_type",
            field=models.CharField(
                choices=[("hourly", "Hourly"), ("fixed", "Fixed price")],
                db_default="hourly",
                default="hourly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="fixed_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
