# Generated by Django 5.1.4 on 2026-08-31 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_visible_on_board'),
        ('tasks', '0002_taskactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskactivity',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Task activities'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='projects.status'),
        ),
    ]
