# Generated by Django 5.1.4 on 2026-08-31 15:00

from django.conf import settings
from django.db import migrations, models


def dedupe_github_issue_ids(apps, schema_editor):
    """Unlink all but the newest task per (project, github_issue_id).

    Existing databases predate the constraint and may hold duplicates from earlier
    webhook replays; without this the AddConstraint below fails.
    """
    Task = apps.get_model('tasks', 'Task')

    keep = {}
    for task in (
        Task.objects.filter(github_issue_id__isnull=False)
        .order_by('project_id', 'github_issue_id', '-pk')
        .iterator()
    ):
        key = (task.project_id, task.github_issue_id)
        if key in keep:
            task.github_issue_id = None
            task.github_issue_number = None
            task.save(update_fields=['github_issue_id', 'github_issue_number'])
        else:
            keep[key] = task.pk


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_phase_b_unique_constraints'),
        ('tasks', '0003_alter_taskactivity_options_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_github_issue_ids, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('github_issue_id__isnull', False)), fields=('project', 'github_issue_id'), name='unique_github_issue_per_project'),
        ),
    ]
