# Generated by Django 5.1.4 on 2026-08-31 15:10

from django.db import migrations


def comments_to_activities(apps, schema_editor):
    """Preserve any ``Comment`` rows as ``TaskActivity`` before the table drops.

    The app never wrote ``Comment`` rows — commenting has always gone through
    ``TaskActivity(activity_type='comment')`` — so in practice this is a no-op.
    It only catches rows typed in by hand through the Django admin on an
    existing install, which would otherwise be lost silently.
    """
    Comment = apps.get_model('tasks', 'Comment')
    TaskActivity = apps.get_model('tasks', 'TaskActivity')

    comments = list(Comment.objects.all().order_by('pk'))
    if not comments:
        return

    activities = [
        TaskActivity(
            task_id=comment.task_id,
            user_id=comment.author_id,
            activity_type='comment',
            content=comment.content,
        )
        for comment in comments
    ]
    TaskActivity.objects.bulk_create(activities)

    # ``TaskActivity.created_at`` is ``auto_now_add``, so the insert above
    # stamped "now" no matter what we passed. ``bulk_update`` writes plain
    # UPDATEs without running ``pre_save``, so it restores the original times.
    for activity, comment in zip(activities, comments, strict=True):
        activity.created_at = comment.created_at
    TaskActivity.objects.bulk_update(activities, ['created_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_phase_b_unique_constraints'),
    ]

    operations = [
        migrations.RunPython(comments_to_activities, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
