# Generated by Django 5.1.4 on 2026-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_list_priority_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytasksfilter',
            name='hidden_statuses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
