# Generated by Django 5.1.4 on 2026-10-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactivity',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='activity_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('status_change', 'Status Changed'), ('assignee_change', 'Assignee Changed'), ('priority_change', 'Priority Changed'), ('created', 'Created'), ('due_date_change', 'Due Date Changed'), ('label_added', 'Label Added'), ('label_removed', 'Label Removed'), ('title_change', 'Title Changed'), ('description_change', 'Description Changed'), ('estimate_change', 'Estimate Changed')], max_length=20),
        ),
    ]
