# Generated by Django 5.1.4 on 2026-10-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_activity_edited_at_and_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
