# Generated by Django 5.1.4 on 2026-10-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0023_task_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="billable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("status_change", "Status Changed"),
                    ("assignee_change", "Assignee Changed"),
                    ("priority_change", "Priority Changed"),
                    ("created", "Created"),
                    ("due_date_change", "Due Date Changed"),
                    ("label_added", "Label Added"),
                    ("label_removed", "Label Removed"),
                    ("title_change", "Title Changed"),
                    ("description_change", "Description Changed"),
                    ("estimate_change", "Estimate Changed"),
                    ("start_date_change", "Start Date Changed"),
                    ("billable_change", "Billable Changed"),
                ],
                max_length=20,
            ),
        ),
    ]
