# Generated by Django 5.1.4 on 2025-12-31 23:46

import apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_token',
            field=apps.accounts.fields.EncryptedCharField(blank=True, help_text='Encrypted at rest', max_length=512),
        ),
    ]
