# Generated by Django 5.1.4 on 2026-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_encrypt_github_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('access_dashboard', models.BooleanField(default=True)),
                ('access_clients', models.BooleanField(default=True)),
                ('access_projects', models.BooleanField(default=True)),
                ('access_tasks', models.BooleanField(default=True)),
                ('access_todos', models.BooleanField(default=True)),
                ('access_notes', models.BooleanField(default=True)),
                ('access_salaries', models.BooleanField(default=True)),
                ('access_team', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System presets cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
