# Generated by Django 5.1.4 on 2026-03-24 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_permission_preset_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.permissionpreset'),
        ),
    ]
