# Generated by Django 5.1.4 on 2026-10-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_invoices_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionpreset",
            name="access_invoices",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="permissionpreset",
            name="access_salaries",
            field=models.BooleanField(default=False),
        ),
    ]
