# Generated by Django 5.1.4 on 2026-10-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_client_archived_at"),
        ("invoices", "0003_invoice_symbol_before"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="clients.client",
            ),
        ),
    ]
