# Generated by Django 5.1.4 on 2026-10-09 09:48

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_client_messages"),
        ("invoices", "0005_recurring_invoices"),
        ("projects", "0019_project_billing_and_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("issue_date", models.DateField()),
                ("valid_until", models.DateField()),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("bill_to_name", models.CharField(max_length=255)),
                ("bill_to_email", models.EmailField(blank=True, max_length=254)),
                ("bill_to_address", models.TextField(blank=True)),
                ("bill_to_tax_id", models.CharField(blank=True, max_length=64)),
                (
                    "company_legal_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("company_address", models.TextField(blank=True, default="")),
                (
                    "company_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "company_tax_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "currency_code",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                (
                    "currency_symbol",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("symbol_before", models.BooleanField(default=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estimates",
                        to="clients.client",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimate",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="EstimateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="invoices.estimate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimate_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_rate__gte", 0), ("tax_rate__lte", 100)),
                name="estimate_tax_rate_between_0_and_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimateline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="estimate_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimateline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="estimate_line_unit_price_non_negative",
            ),
        ),
    ]
