# Generated by Django 5.1.4 on 2026-10-09 10:20

import django.db.models.deletion
from django.db import migrations, models


def fill_project(apps, schema_editor):
    """An invoice or estimate whose lines all name the same project gets that project."""
    for model_name in ('Invoice', 'Estimate'):
        model = apps.get_model('invoices', model_name)
        for document in model.objects.filter(project__isnull=True).prefetch_related('lines'):
            projects = {line.project_id for line in document.lines.all()}
            if len(projects) == 1 and None not in projects:
                model.objects.filter(pk=document.pk).update(project_id=projects.pop())


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_estimates"),
        ("projects", "0019_project_billing_and_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimates",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="projects.project",
            ),
        ),
        migrations.RunPython(fill_project, migrations.RunPython.noop),
    ]
