# Generated by Django 5.1.4 on 2026-10-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0007_invoice_project"),
        ("tasks", "0025_timeentry_user_protect"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_lines",
                to="tasks.task",
            ),
        ),
    ]
