# Generated by Django 5.1.4 on 2026-10-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0008_invoiceline_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimateline",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="details",
            field=models.TextField(blank=True),
        ),
    ]
