from django.urls import path

from . import views

urlpatterns = [
    path('my/', views.my_tasks, name='my_tasks'),
    path('my/todos/', views.my_tasks, name='my_tasks_todos'),
    path('my/week/', views.time_week, name='time_week'),
    path('timer/stop/', views.timer_stop, name='timer_stop'),
    path('timer/indicator/', views.running_timer_indicator, name='running_timer_indicator'),
    path('time/<int:entry_pk>/edit/', views.time_entry_edit, name='time_entry_edit'),
    path('time/<int:entry_pk>/delete/', views.time_entry_delete, name='time_entry_delete'),
    path('move/', views.task_move, name='task_move'),
    path('markdown/preview/', views.markdown_preview, name='markdown_preview'),
    path('project/<int:project_pk>/create/', views.task_create, name='task_create'),
    path('<int:pk>/', views.task_detail, name='task_detail'),
    path('<int:pk>/time-property/', views.task_time_property, name='task_time_property'),
    path('<int:pk>/timer/start/', views.timer_start, name='timer_start'),
    path('<int:pk>/time/log/', views.time_log, name='time_log'),
    path('<int:pk>/edit/', views.task_edit, name='task_edit'),
    path('<int:pk>/quick/<str:field>/', views.task_quick_menu, name='task_quick_menu'),
    path('<int:pk>/status/', views.task_update_status, name='task_update_status'),
    path('<int:pk>/delete/', views.task_delete, name='task_delete'),
    path('<int:pk>/subtasks/', views.subtask_create, name='subtask_create'),
    path('<int:pk>/subtasks/<int:subtask_pk>/toggle/', views.subtask_toggle, name='subtask_toggle'),
    path('<int:pk>/subtasks/<int:subtask_pk>/delete/', views.subtask_delete, name='subtask_delete'),
    path('<int:pk>/subtasks/<int:subtask_pk>/rename/', views.subtask_rename, name='subtask_rename'),
    path('<int:pk>/subtasks/reorder/', views.subtask_reorder, name='subtask_reorder'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:pk>/comments/<int:comment_pk>/edit/', views.comment_edit, name='comment_edit'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/subscription/', views.task_subscription, name='task_subscription'),
    path('<int:pk>/activity/', views.task_activity_list, name='task_activity_list'),
    path('<int:pk>/attachments/', views.attachment_upload, name='attachment_upload'),
    # Full page task view
    path('project/<int:project_pk>/<int:task_pk>/', views.task_full_page, name='task_full_page'),
    # Property update endpoints
    path('<int:pk>/assignee/', views.task_update_assignee, name='task_update_assignee'),
    path('<int:pk>/priority/', views.task_update_priority, name='task_update_priority'),
    path('<int:pk>/due-date/', views.task_update_due_date, name='task_update_due_date'),
    path('<int:pk>/estimate/', views.task_update_estimate, name='task_update_estimate'),
    path('<int:pk>/labels/<int:label_pk>/toggle/', views.task_toggle_label, name='task_toggle_label'),
    path('<int:pk>/description/', views.task_edit_description, name='task_edit_description'),
    path('<int:pk>/title/', views.task_edit_title, name='task_edit_title'),
]
