# Generated by Django 5.1.4 on 2026-10-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
