# Generated by Django 5.1.4 on 2026-10-08 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_client_archived_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("is_primary", models.BooleanField(db_default=False, default=False)),
                ("is_billing", models.BooleanField(db_default=False, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-is_billing", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("client",),
                        name="one_primary_contact_per_client",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_billing", True)),
                        fields=("client",),
                        name="one_billing_contact_per_client",
                    ),
                ],
            },
        ),
    ]
