# Generated by Django 5.1.4 on 2026-10-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_client_messages"),
        ("invoices", "0006_estimates"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmessage",
            name="estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails",
                to="invoices.estimate",
            ),
        ),
    ]
